import express from "express";
import { ProductRouter } from "@/common/product/product-controller.js";
import { RoleClaimRoute } from "@/account/role-claim/role-claim-controller.js";
import { CustomerRouter } from "@/common/customer/customer-controller.js";
import { OrderRouter } from "@/common/order-sale/order/order-controller.js";
import { SaleRouter } from "@/common/order-sale/sale/sale-controller.js";
import { PaymentRouter } from "@/common/payment/payment-controller.js";
import { StaffRouter } from "@/common/staff/staff-controller.js";
import { TenantSettingRoute } from "@/common/tenant/tenant-setting/tenant-setting-controller.js";
import { UserRouter } from "../account/user/user-controller.js";
import { AuthRouter } from "../account/auth/auth-controller.js";
const myRouter = express.Router();
myRouter.use("/product", [ProductRouter]);
myRouter.use("/staff", [StaffRouter]);
myRouter.use("/customer", [CustomerRouter]);
myRouter.use("/order", [OrderRouter]);
myRouter.use("/sale", [SaleRouter]);
myRouter.use("/payment", [PaymentRouter]);
myRouter.use("/setting", [TenantSettingRoute]);
myRouter.use("/role-claim", [RoleClaimRoute]);
myRouter.use("/user", [UserRouter]);
myRouter.use("/auth", [AuthRouter]);
export const ApiRoutesResolver = myRouter;
//# sourceMappingURL=main.js.map